server {
  listen 8888;
  server_name localhost 127.0.0.1 client.com;

  location / {
    proxy_pass  http://app_servers;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header CF-Connecting-IP "";
	if ($request_method = 'OPTIONS') {
	    add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Headers 'Origin,DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
     	return 204;
  	}
  }
}
