export default {
    ddgl_Dsdd: {
        channel_code: "number",
        amount: "number",
        status: "number",
        merchant_id: "number",
        partner_id: "number",
        payment_id: "number",
        realpay: "number",
        merchant_rate : "number",
        poundage: "number",
        earn_merchant: "number",
        earn_partner: "number",
        earn_system: "number",
    },
    ddgl_Dsddcd: {
        channel_code: "number",
        amount: "number",
        status: "number",
        merchant_id: "number",
        partner_id: "number",
        payment_id: "number",
        realpay: "number",
        merchant_rate : "number",
        poundage: "number",
        earn_merchant: "number",
        earn_partner: "number",
        earn_system: "number",
    },
    ddgl_Dfdd: {
        amount: "number",
        status: "number",
        merchant_id: "number",
        partner_id: "number",
        payment_id: "number",
        realpay: "number",
        merchant_rate : "number",
        poundage: "number",
        earn_merchant: "number",
        earn_partner_self: "number",
        earn_system: "number",
    },
    ddgl_Mstxdd: {
        amount: "number",
        amount_success: "number",
        amount_order: "number",
    },
    ddgl_Msczdd: {
        amount: "number",
    },
    ddgl_Msczddss: {
        payoutSum: "number",
        usdtSum: "number",
        sum: "number",
    },
    ddgl_Msusdtczdd: {
        total_amount: "number",
        bonus: "number",
        currency_amount: "number",
        usdt_amount: "number",
    },
    ddgl_Mszzdd: {
        amount: "number",
    },
    ddgl_Shtxdd: {
        amount: "number",
        amount_success: "number",
        amount_order: "number",
    },
    zjls_Yels: {
        user_id: "number",
        change_before: "number",
        amount: "number",
        change_after: "number",
        record_type: "number",
    },
    msgl_Mslb: {
        id: "number",
        pid: "number",
        vip: "number",
        balance: "number",
        balance_frozen: "number",
        type: "number",
        balance_deposit: "number",
    },
};
