apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-fingerprint-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  local:
    path: /data/pk/api/fingerprint
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pk-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-fingerprint-pvc
  namespace: pk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
  volumeName: api-fingerprint-pv
