apiVersion: v1
kind: Secret
metadata:
  name: d7pay-runtime-secret
  namespace: pk-d7pay
  labels:
    tenant: d7pay
type: Opaque
stringData:
  MYSQL_USER: d7pay_app
  MYSQL_PASSWORD: replace-in-jenkins
  API_KEY_ORDER: replace-in-jenkins
  API_SECRET_KEY: replace-in-jenkins
  ADMIN_COOKIE_KEY: replace-in-jenkins
  ADMIN_ID_TOKEN_KEY: replace-in-jenkins
  MERCHANT_COOKIE_KEY: replace-in-jenkins
  EASYPAISA_API_URL: replace-in-jenkins
  EASYPAISA_USER_ID: replace-in-jenkins
  EASYPAISA_SECRET_KEY: replace-in-jenkins
  JAZZCASH_API_URL: replace-in-jenkins
  JAZZCASH_USER_ID: replace-in-jenkins
  JAZZCASH_SECRET_KEY: replace-in-jenkins
---
apiVersion: v1
kind: Secret
metadata:
  name: d7pay-android-signing
  namespace: pk-d7pay
  labels:
    tenant: d7pay
type: Opaque
stringData:
  key.properties: |
    storeFile=/workspace/android/app/shared-release.keystore
    storePassword=replace-in-jenkins
    keyAlias=replace-in-jenkins
    keyPassword=replace-in-jenkins
