apiVersion: v1
kind: PersistentVolume
metadata:
  name: d7pay-workerlog-worker-pv
  labels:
    tenant: d7pay
    app: d7pay-go-worker
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  local:
    path: /data/pk-d7pay/workerlog/worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pk-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: d7pay-workerlog-worker-pvc
  namespace: pk-d7pay
  labels:
    tenant: d7pay
    app: d7pay-go-worker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: d7pay-workerlog-worker-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: d7pay-workerlog-relay-pv
  labels:
    tenant: d7pay
    app: d7pay-go-worker-relay
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  local:
    path: /data/pk-d7pay/workerlog/relay
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pk-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: d7pay-workerlog-relay-pvc
  namespace: pk-d7pay
  labels:
    tenant: d7pay
    app: d7pay-go-worker-relay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: d7pay-workerlog-relay-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: d7pay-workerlog-scheduler-pv
  labels:
    tenant: d7pay
    app: d7pay-go-worker-scheduler
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  local:
    path: /data/pk-d7pay/workerlog/scheduler
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pk-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: d7pay-workerlog-scheduler-pvc
  namespace: pk-d7pay
  labels:
    tenant: d7pay
    app: d7pay-go-worker-scheduler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: d7pay-workerlog-scheduler-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: d7pay-workerlog-ops-pv
  labels:
    tenant: d7pay
    app: d7pay-go-worker-ops
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  local:
    path: /data/pk-d7pay/workerlog/ops
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pk-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: d7pay-workerlog-ops-pvc
  namespace: pk-d7pay
  labels:
    tenant: d7pay
    app: d7pay-go-worker-ops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: d7pay-workerlog-ops-pv
