spec:
  template:
    metadata:
      labels:
        tenant: d7pay
    spec:
      containers:
        - name: merchant
          envFrom:
            - configMapRef:
                name: d7pay-config
            - secretRef:
                name: d7pay-secret
