version: '3'
services:
  db:
    image: mysql:8.3
    restart: always
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwer4321
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
      TZ: UTC
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=caching_sha2_password
    volumes:
      - mysql-data-volume:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d
  app: &app_base
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/root/.ssh:ro
      - python_lib_volume:/usr/local/lib
    depends_on:
      - db
      - redis
      - nginx

  app_0:
    <<: *app_base
    container_name: app_0
    command: bash -c 'RUN_ENV=DEV python main.py --port=9000'
    ports:
      - "9000:9000"

  app_1:
    <<: *app_base
    container_name: app_1
    command: bash -c 'RUN_ENV=DEV python main.py --port=9001'
    ports:
      - "9001:9001"

  app_2:
    <<: *app_base
    container_name: app_2
    command: bash -c 'RUN_ENV=DEV python main.py --port=9002'
    ports:
      - "9002:9002"

  redis:
    image: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "9379:6379"
    volumes:
      - 'redis:/data'

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/ospay_api.conf:/etc/nginx/sites-enabled/ospay_api.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    ports:
      - "8888:8888"

volumes:
  mysql-data-volume:
  redis:
  python_lib_volume:
